WebApplicationUnip2022/Models/EnderecoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Models
{
    public class EnderecoModel
    {
        public int Id { get; set; }
        public string Logradouro { get; set; }
        public int NumeroCasa { get; set; }
        public long Cep { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
    }
}

WebApplicationUnip2022/Models/ErrorViewModel.cs
using System;

namespace WebApplicationUnip2022.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplicationUnip2022/Models/PessoaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Models
{
    public class PessoaModel
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public long Cpf { get; set; }
        public string Endereco { get; set; }
        public long Telefone { get; set; }
    }
}

WebApplicationUnip2022/Models/TelefoneModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Models
{
    public class TelefoneModel
    {
        public int Id { get; set; }
        public long Telefone { get; set; }
        public int DDD { get; set; }
        public string Tipo { get; set; }
    }
}

WebApplicationUnip2022/Controllers/EnderecoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Controllers
{
    public class EnderecoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CriarEndereco()
        {
            return View();
        }

        public IActionResult EditarEndereco()
        {
            return View();
        }
        public IActionResult DeletarEndereco()
        {
            return View();
        }
    }
}

WebApplicationUnip2022/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplicationUnip2022.Models;

namespace WebApplicationUnip2022.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            //instancia da pessoa
            PessoaModel pessoa = new PessoaModel();

            pessoa.Id = 123;
            pessoa.Nome = "Galeto Junior";
            pessoa.Cpf = 456712348910;
            pessoa.Endereco = "Rua Pelé Eterno";
            pessoa.Telefone = 11987451234;

            return View(pessoa);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplicationUnip2022/Controllers/PessoaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Controllers
{
    public class PessoaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar()
        {
            return View();
        }
        public IActionResult Deletar()
        {
            return View();
        }


    }
}

WebApplicationUnip2022/Controllers/TelefoneController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplicationUnip2022.Controllers
{
    public class TelefoneController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CriarTelefone()
        {
            return View();
        }

        public IActionResult EditarTelefone()
        {
            return View();
        }
        public IActionResult DeletarTelefone()
        {
            return View();
        }
    }
}

WebApplicationUnip2022/Views/Endereco/CriarEndereco.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationUnip2022/Views/Endereco/DeletarEndereco.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationUnip2022/Views/Endereco/EditarEndereco.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationUnip2022/Views/Home/About.cshtml
@{
    ViewData["Title"] = "Sobre os membros de nosso trabalho ";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Membros do grupo:</p>
<ol>
    
    <li><a href="https://www.linkedin.com/in/jade-maria-467883164/">Jade Maria</a></li>
    <li><a href="https://www.linkedin.com/in/laryssa-p%C3%A9per-119502137/">Laryssa Péper</a></li>
    <li><a href="https://www.linkedin.com/in/saulo-vilela-barbosa-531902130/">Saulo Vilela</a></li>
    <li><a href="https://www.linkedin.com/in/thiagomaciel19/">Thiago Eid</a></li>
    <li><a href="https://github.com/Vinicius029">Vinícius</a></li>
</ol>

WebApplicationUnip2022/Views/Home/Index.cshtml
@model PessoaModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <h1 class="display-4">Bem vindo, @Model.Nome</h1>
    <p>Site em MVC</p>
    <span>Seu Id é : @Model.Id</span>

</div>

WebApplicationUnip2022/Views/Pessoa/Criar.cshtml
@{
    ViewData["Title"] = "Criar Contatos";
}
<div class="text-left">
    <h1 class="display-4">Cadastrar Pessoa</h1>

</div>
<br />
<h3>Dados Pessoais</h3>

<form>
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o Nome">
    </div>
    <div class="form-group">
        <label for="Nome">CPF</label>
        <input type="text" class="form-control" placeholder="Digite o CPF">
    </div>
</form>
<br />
<h3>Endereço</h3>
<form>
    <div class="form-group">
        <label for="Nome">Cidade</label>
        <input type="text" class="form-control" placeholder="Digite a Cidade">
    </div>
    <div class="form-group">
        <label for="Nome">Estado</label>
        <input type="text" class="form-control" placeholder="Digite o Estado">
    </div>
    <div class="form-group">
        <label for="Nome">CEP</label>
        <input type="text" class="form-control" placeholder="Digite o CEP">
    </div>
</form>
<h3>Telefone</h3>
<form>
    <div class="form-group">
        <label for="Nome"></label>
        <input type="text" class="form-control" placeholder="Digite o telefone">
    </div>
    <h4>tipo de telefone</h4>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
        <label class="form-check-label" for="exampleRadios1">
            Telefone Fixo
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
        <label class="form-check-label" for="exampleRadios2">
            Celular
        </label>
    </div>
</form>

WebApplicationUnip2022/Views/Pessoa/Deletar.cshtml
@{
    ViewData["Title"] = "Deletar Contatos";
}
<div class="text-center">
    <h3 class="display-4">Realmente gostaria de deletar este contato?</h3>

    <a role="button" class="btn btn-primary btn-block" asp-controller="Pessoa"asp-action="Index">Cancelar Exclusão</a>
    <a role="button" class="btn btn-danger btn-block"asp-controller="Pessoa"asp-action="Apagar">Confirmar Exclusão</a>

WebApplicationUnip2022/Views/Pessoa/Editar.cshtml
@{
    ViewData["Title"] = "Editar Contato";
}
<div class="text-left">
    <h1 class="display-4">Editar Contato</h1>

</div>
<br />
<h3>Dados Pessoais</h3>

<form>
    <div class="form-group">
        <label for="Nome">Nome</label>
        <input type="text" class="form-control" placeholder="Digite o Nome">
    </div>
    <div class="form-group">
        <label for="Nome">CPF</label>
        <input type="text" class="form-control" placeholder="Digite o CPF">
    </div>
</form>
<br />
<h3>Endereço</h3>
<form>
    <div class="form-group">
        <label for="Nome">Cidade</label>
        <input type="text" class="form-control" placeholder="Digite a Cidade">
    </div>
    <div class="form-group">
        <label for="Nome">Estado</label>
        <input type="text" class="form-control" placeholder="Digite o Estado">
    </div>
    <div class="form-group">
        <label for="Nome">CEP</label>
        <input type="text" class="form-control" placeholder="Digite o CEP">
    </div>
</form>
<h3>Telefone</h3>
<form>
    <div class="form-group">
        <label for="Nome"></label>
        <input type="text" class="form-control" placeholder="Digite o telefone">
    </div>
    <h4>tipo de telefone</h4>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios1" value="option1" checked>
        <label class="form-check-label" for="exampleRadios1">
            Telefone Fixo
        </label>
    </div>
    <div class="form-check">
        <input class="form-check-input" type="radio" name="exampleRadios" id="exampleRadios2" value="option2">
        <label class="form-check-label" for="exampleRadios2">
            Celular
        </label>
    </div>
</form>

WebApplicationUnip2022/Views/Pessoa/Index.cshtml
@{
    ViewData["Title"] = "Listagem de contatos";
}
<div class="text-left">
    <div class="btn-group" role="group">
        <a role="button" class="btn btn-primary"asp-controller="Pessoa"asp-action="Criar">Cadastrar</a>
        <a role="button" class="btn btn-info">Adicionar</a>
    </div>
    <br />
    <p><h2>Lista de pessoas</h2></p>

</div>
<table class="table">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Pessoa</th>
            <th scope="col">Endereço</th>
            <th scope="col">Telefone</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th scope="row">1</th>
            <td>Markos</td>
            <td>Otto</td>
            <td>11900000000</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning"asp-controller="Pessoa"asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger"asp-controller="Pessoa"asp-action="Deletar">Deletar</a>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>11900000000</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning"asp-controller="Pessoa"asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger"asp-controller="Pessoa"asp-action="Deletar">Deletar</a>
                </div>
            </td>
        </tr>
        <tr>
            <th scope="row">3</th>
            <td>Pelé</td>
            <td>Thornton</td>
            <td>11900000000</td>
            <td>
                <div class="btn-group" role="group">
                    <a role="button" class="btn btn-warning"asp-controller="Pessoa"asp-action="Editar">Editar</a>
                    <a role="button" class="btn btn-danger"asp-controller="Pessoa"asp-action="Deletar">Deletar</a>
                </div>
            </td>
        </tr>
    </tbody>
</table>

WebApplicationUnip2022/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PIM tela de cadastro</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">PIM tela de cadastro</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Tela Principal</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">Sobre</a></li>
                    <li><a asp-area="" asp-controller="Pessoa" asp-action="Index">Contato</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2022 - PIM tela de cadastro</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplicationUnip2022/Views/Telefone/CriarTelefone.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationUnip2022/Views/Telefone/DeletarTelefone.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

WebApplicationUnip2022/Views/Telefone/EditarTelefone.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}